### ISSUE TITLE
Evaluation-metric

### ISSUE THREAD

**Issue by Tawnado** [recsyschallenge/2017#10]
Hello, 

I would have a question regarding the evaluation metric. From a quick look at the data I gather users sometimes delete a job after having clicked on it (or even bookmarked it). Am I right in presuming we don't incur a 10 point penalty for them? 

Thank you very much! 

Best wishes,
Alex

**Comment by dkohlsdorf** [comment]
Yes exactly, you only get a penalty whenever the job was only deleted.

Daniel

**Comment by Tawnado** [comment]
Thanks! 

Alex
