### ISSUE TITLE
Team membership on XING

### ISSUE THREAD

**Issue by raphaelfournier** [recsyschallenge/2017#12]
I am willing to participate to the challenge with another researcher. We both have created an account on Xing.de. She created a team, but neither her nor me can find a way for me to join the approved team. Does it mean that only one person per team is authorized to submit solutions on the platform? 
(I don't think sharing her credentials for the whole Xing platform would be a good practice)

**Comment by fabianabel** [comment]
Yeah, that's currently a limitation of the system. I am back in the office on Friday and will then work on a solution. I'll comment in this ticket as soon as we deployed a solution.

**Comment by fabianabel** [comment]
We now deployed a first version of an API (see [API description](https://github.com/recsyschallenge/2017/tree/master/api#submission-system-api-alpha-version)). If you share the access token among your team mates, you can allow your team members to also submit solutions...
