### ISSUE TITLE
Maximum score per (user,item) pair

### ISSUE THREAD

**Issue by abdollahpouri** [recsyschallenge/2017#13]
Hello, 

I have a question regarding the logic behind the score calculation.
In the challenge website it says:
"At maximum, one can thus earn 52 points (= (1 + 5 + 20 - 0) * 2) per user-item pair."

Does this mean a (user, item) pair can have multiple interaction_type?

**Comment by fabianabel** [comment]
Hi @himanData,

yes, for a `(user u1, item i1)` pair we may observe the following three interactions:

- user `u1` clicks on item `i1`
- `u1` bookmarks `i1` or clicks on apply/reply button (see screenshot below: the buttons at the top right of a job ad)
- the recruiter that is recruiting for `i1` clicked on the profile of `u1`

If you algorithm would thus correctly predict that `u1` might be interested in `i1` and `u1` has a premium subscription then this would give you 52 points. 

<img width="994" alt="screen shot 2017-03-08 at 22 05 16" src="https://cloud.githubusercontent.com/assets/1157818/23723968/6baf8c84-044b-11e7-8dff-a9083f79e9ac.png">

Cheers,
fabian

**Comment by abdollahpouri** [comment]
Thanks. In this case, I think your baseline code does something different. 

In parser.py line 35, it stores the interactions data as a dictionary that the key is (userId, itemId), which means you only store one interaction per (user, item). If I am right, I think your baseline algorithm could get higher score than 10004. Please correct me if I am wrong.

Thanks

**Comment by dkohlsdorf** [comment]
actually no ... the baseline is not directly computing the score bit trying to predict which postings match which users ... independent of the acoring function

daniel

**Comment by abdollahpouri** [comment]
I agree but don't you use that interaction dictionary for other parts of the code? I mean, the solution is generated based on the assumption that the dictionary has unique interactions for (user, item) pairs. Maybe changing that would generate different results and therefore different score. 
We, as participants, wouldn't mind if you are still happy with 10004 :)

Thanks,
Himan
