### ISSUE TITLE
Target Users

### ISSUE THREAD

**Issue by DaveXster** [recsyschallenge/2017#15]
Hi All!

There are 1,497,020 users in the users catalog.  The number of target users is 74840, which is 4.9992% of the total number of users.

How is the list of target users defined? Is it a 5% random sample of the total catalog?
If not, can we know something more specific about the sampling logic?

Thanks,
David

**Comment by fabianabel** [comment]
Hi David, 
the set of target users is a randomly selected subset of those users who were active on XING during the test period. 
Cheers,
fabian
