### ISSUE TITLE
success() function not defined in evaluation

### ISSUE THREAD

**Issue by manoj1992** [recsyschallenge/2017#18]
Hi,

In the itemSuccess() function, I believe the success(item, u) method is not defined, or maybe I am not understanding it correctly.
Does it mean that the user u positively interacted (click or bookmark) with the item?
Thanks.

**Comment by fabianabel** [comment]
Thank you for spotting this. It should be `userSuccess` not `success`: `if (users.filter(u => userSuccess(item, u) > 0).size > 1)...` We [changed it](https://github.com/recsyschallenge/2017/commit/c8cb392f6730b476fa5f39dcadaec8d20be0e1f1). 
Thank you,
fabian
