### ISSUE TITLE
Question about evaluation metric

### ISSUE THREAD

**Issue by mattiadagrada** [recsyschallenge/2017#21]
I found out something that looks like an inconsistency between your description of the evaluation metric and your pseudocode:
- in the pseudocode we can read
` if (users.filter(u => success(item, u) > 0).size > 1) `
- while in the description it says
> itemSuccess(item, users) if at least one successful push recommendation was created for a given item then this counts 50 points for paid items and 25 for other items.

Which one should we consider correct? 
Thanks in advance

**Comment by fabianabel** [comment]
Thank you for spotting this! It should be: `...userSuccess(item, u) > 0)` not `...success(item, u)`. Anyways, the pseudo code and textual description should mean the same thing: `users.filter(u => userSuccess(item, u) > 0)` (Scala-like pseudo code) should give you those users for whom we observe a successful push recommendation (for the given `item`) - where _successful_ means: `userSuccess(item, u) > 0`.

**Comment by mattiadagrada** [comment]
Yeah but my question was more about the :

if (users.filter(u => userSuccess(item, u) > 0) .**size > 1**)

while in the description you say :

if at least **ONE** successful push recommendation

Is that supposed to be size > 0 or am I missing something here? 
thanks

**Comment by fabianabel** [comment]
Yes, correct. Changed it correspondingly.
Thank you,
fabian
