### ISSUE TITLE
baseline details about file "xgb.py"

### ISSUE THREAD

**Issue by phsimon** [recsyschallenge/2017#23]
Hi,

In this file, in github, in line 57, one can read "param['nthread'] = 4" and in line 59 "param['nthread'] = 5".
Is it OK ?

Another question, the comment says, max depth for the tree 6, but in line 56, one can read "'bst:max_depth': 2" ?

Best regards.

**Comment by dkohlsdorf** [comment]
Good catch the actual value of the depth is correct ... I forgot to adjust the comment.
With the threads I forgot to delete the first param. But the script is running ok. However,
the cleanup is commited.

Daniel
