### ISSUE TITLE
Why is there a 6 weeks period with no interactions in the dataset?

### ISSUE THREAD

**Issue by danielegrattarola** [recsyschallenge/2017#25]
We found this "hole" in the interactions dataset a few days ago, but we couldn't understand if it was intentional or a mistake. 
![scatter_created_at_item_id](https://cloud.githubusercontent.com/assets/11634240/24204700/9270fe9c-0f19-11e7-8a9c-a8238ec69efa.png)
In the plot above we have item ids on the y axis and time on the x axis. 
A dot on the plot is an interaction (of type 1, 2, 3 or 4) with item y at time t. 

Something similar happens with the users:
![scatter_created_at_user_id](https://cloud.githubusercontent.com/assets/11634240/24204901/2aa7d9ec-0f1a-11e7-838d-95cbf0c1bd5a.png)
And in general (if we only plot interactions at a given time):
![scatter_created_at_created_at](https://cloud.githubusercontent.com/assets/11634240/24205044/8eb8c22a-0f1a-11e7-97df-08d388fe12ee.png)
Can you give us some more details about this?

Thanks, 
Daniele

**Comment by dkohlsdorf** [comment]
Hi, we are sorry but we had an error in our dataset creation scripts. We sorted the interactions in weekly buckets and lost some in our queries. However, this should not effect you much.

Sorry again,
Daniel

**Comment by skywaLKer518** [comment]
Hey Daniel,

Is the 'testing data' around 1480 000000 or around 1486 000000? It does make a difference in splitting train/validation or if temporal dynamics are taken into consideration.

at first we thought the interactions start from end of previous year and go across the end of the year... 

Thanks for clarifying!
