### ISSUE TITLE
Questions about the online challenge

### ISSUE THREAD

**Issue by fciceri17** [recsyschallenge/2017#32]
Good morning,

Over the course of the past week I have been looking at the rules for the online part of the challenge. I have several questions to ask regarding these rules:
1) How is the final leaderboard calculated? Will the best 2 daily submissions be considered or will the best 2 weeks be considered, with all the submissions in those 2 weeks?
2) In the evaluation function for the offline challenge, part of the score is given by the item_success function, where 25 points are awarded per item. Will this item_success bonus be applied also during the online portion?
3) Regarding day-by-day scoring, will we receive any feedback from our submissions? If so, how frequently will our scores be updated? Also, will there be a leaderboard like in the offline portion?
4) Will different teams receive the same set or subset of target users and items? If so, can this happen on the same day or only on different days?

Thanks

**Comment by Matt8white** [comment]
UP

**Comment by dkohlsdorf** [comment]
1) The best weeks not days
2) Yes all bonuses apply
3) We plan to update the score on a daily bases
4) A subset of users but all the same items. The subset changes daily
