### ISSUE TITLE
Number of target users/items per day in online challenge

### ISSUE THREAD

**Issue by hackebeil** [recsyschallenge/2017#34]
Hi.

In the online challenge, new target users and items are released every day. It is also mentioned in the API description that each user can only receive one recommendation. 

My question in this context is: How many items and users will there be per day? Ballpark numbers or just the ratio between the two numbers would already be helpful.

An example for why this is important: If we get 100 users and 100 items each day, recommending every item to at least one user becomes a challenge in itself due to the "only one recommendation per user" restriction. So having a general idea about the ratio between users and items per day would be helpful.

Cheers

**Comment by dkohlsdorf** [comment]
Target Users: ~50000
The number of items depends on how many new items xing gets that day

Daniel
