### ISSUE TITLE
questions about the timeline

### ISSUE THREAD

**Issue by Leavingseason** [recsyschallenge/2017#35]
Hello ,  I have two questions,
(1) which time zone do you use for counting each day?
     Since the new items will expire after 24 hours, time zone seems to be an extremely important message.
(2)  I am not quite understand what this means：
 “the final leaderboard score is not calculated over all submissions but over the two best weeks”
could you explain what is "two best weeks"?
Thanks!

**Comment by dkohlsdorf** [comment]
(1) 24 hours after the release of the data.
(2) The final score for each team is composed of the two best scores accumulated over a week
