### ISSUE TITLE
There are users who are in interactions.csv but not in users.csv.

### ISSUE THREAD

**Issue by god-hirosi** [recsyschallenge/2017#36]
Hello, 
We checked the files for online evaluation and found that there are many users who are only in  interactions.csv (who are not in users.csv).
n(users) in interactions.csv: 691736
n(users) in both interactions.csv and users.csv(for online): 340885
n(users) in both interactions.csv and users.csv(for online and offline): 365160

Should we ignore them or will you give us additional contents file?
In online evaluation, are target users only in users.csv for online?

Thanks, 
team chome

**Comment by dkohlsdorf** [comment]
I will check that,
thanks for the pointer, 

Daniel

**Comment by dkohlsdorf** [comment]
Actually can you describe how you got these numbers?

Daniel

**Comment by god-hirosi** [comment]
We got those numbers when excluding impression logs.
We tried when including them.
We write a python code and numbers as follows.
```python
import pandas as pd
df = pd.read_csv('recsys2017/online/interactions.csv', delimiter='\t')
df.columns = [col.split('.')[1] for col in df.columns]
us_new = pd.read_csv('recsys2017/online/users.csv', delimiter='\t')
us_new.columns = [col.split('.')[1] for col in us_new.columns]
us_old = pd.read_csv('recsys2017/data_2017/users.csv', delimiter='\t')
us_old.columns = [col.split('.')[1] for col in us_old.columns]

us_inInt = set(df['user_id'].drop_duplicates().values.tolist()) # user set in interactions.csv
us_inNew = set(us_new['id'].drop_duplicates().values.tolist()) # user set in users.csv(online)
us_inOld = set(us_old['id'].drop_duplicates().values.tolist()) # user set in users.csv(offline)

# n_users in interactions.csv: 948325
print len(us_inInt) 
# n_users in both interactions.csv and users.csv(for online): 467700
print len(us_inInt.intersection(us_inNew))
# n_users in both interactions.csv and users.csv(for online): 500942
print len(us_inInt.intersection(us_inNew | us_inOld))
```

team chome

**Comment by dkohlsdorf** [comment]
Ok you can check again, all should be fine now :) thanks again for the hint
