### ISSUE TITLE
Hadoop logs are downloaded as part of the response when using the API

### ISSUE THREAD

**Issue by danielegrattarola** [recsyschallenge/2017#37]
Hi,
I don't know if we're not supposed to be using the API for the online challenge yet, but I've tried to download the data through it and I've noticed that both the items and interactions endpoints return what seem to be Hadoop logs as part of the response.
Here's an example of trailing text when polling the interactions endopoint, but similar errors appear also in the middle of the response

Is this a problem on our end?
Thanks,
Daniele

**Comment by dkohlsdorf** [comment]
Will look into it … i thought i fixed it :(
Daniel
