### ISSUE TITLE
Access to the online api

### ISSUE THREAD

**Issue by ksharmar** [recsyschallenge/2017#41]
Have other teams who submitted the description and NDA been able to see the button on the team page for the online round API and token? 
It is still not visible for us? @dkohlsdorf 

Team Amethyst.

**Comment by dkohlsdorf** [comment]
We are not able to give you access to the challenge until we checked the changes you made to the NDA with us.
As mentioned earlier to your team, this might take a while and we can’t promise that we will make it in time

Daniel
