### ISSUE TITLE
difference of users/items between offline stage and online stage

### ISSUE THREAD

**Issue by Leavingseason** [recsyschallenge/2017#42]
hi,  I found that the newly provided items.csv and uers.csv have many overlapped IDs with the offline stage's items.csv and users.csv, however,  the profile is totally different. I am confused about these files. 
Do you mean the IDs are re-hashed since the online stage,  and we should not use the data released in the offline stage?

**Comment by dkohlsdorf** [comment]
The ids are re-anonymized so they do not point to the same item / user in the new set.
However, the fields meaning stayed the same. if you want to use both datasets
you could offset the new user ids by the number of users in the old set and
also do the same for the interactions

Daniel

**Comment by Leavingseason** [comment]
So the titles and tags are not re-anonymized?  For instance, the word "1757461" point to the same token in offline stage and online stage?

**Comment by dkohlsdorf** [comment]
Exactly
