### ISSUE TITLE
Differences in dataset schemas

### ISSUE THREAD

**Issue by admdns** [recsyschallenge/2017#43]
Hi! The following differences in dataset schemas are a tiny source of frustration in automated scripts ... 

1- ) Offline users.csv has 14 columns with "wtcj" in column 13. Online users.csv has 13 columns lacking "wtcj".

2-) The order of columns in item.csv are different in all of the three files (offline item.csv, online item.csv (history), online item.csv (last incremental version as of 29.04) )

3-) The order of columns in interactions.csv is different in offline and online versions.

Can you please decide the final schemas as soon as possible ?

**Comment by dkohlsdorf** [comment]
1) WTCJ is all high for the online dataset so it is omitted here.
2-3) Yes it changed sorry

I can normalize the online updates to online training today

Daniel

**Comment by admdns** [comment]
Yes, please normalize them.

**Comment by dkohlsdorf** [comment]
Ok so the interactions will not change, the online training and online data will be the same.
The items are normalised and I am currently uploading a new file. Should be done in about an hour

Hope that helps,
Daniel

**Comment by admdns** [comment]
Sounds fine, thanks.

**Comment by admdns** [comment]
Online training and online data have not been aligned :(  So, should I assume that it will not be?

**Comment by dkohlsdorf** [comment]
Not yet, 
will be done by tomorrow morning.
Also there will be no overlap between postings in training and online

Daniel

**Comment by dkohlsdorf** [comment]
btw please shoot me an email so we can chat somehow.
