### ISSUE TITLE
Items are different at online stage

### ISSUE THREAD

**Issue by Leavingseason** [recsyschallenge/2017#44]
Hi, I found that even at the online stage, items provided in different files are not consistent. 
Some  items from  https://recsys.xing.com/data/online  have same ID with  items got from /api/online/data/items' , however, their profile are different.  How to understand this?

**Comment by dkohlsdorf** [comment]
The items are anonymized per day, too.

Daniel

**Comment by dkohlsdorf** [comment]
The items right now are anonymized per day.
Since the target items will only be valid for a day. However, we have to track this through the interaction log.

Will think about this today

Daniel

**Comment by admdns** [comment]
Does that mean we will not be able to append directly
- a day's interactions to past interactions and 
- a day's target items to the items file until then   ?

A related question is
when looking at items.csv and interactions.csv from days 29.04 and 30.04, items.csv has a yuge overlap with interactions.csv items. Then has the problem changed, how come this is a cold start item problem? or do I need a break :)

**Comment by dkohlsdorf** [comment]
Well you will be able to append since I fixed it.
I will deploy the new solution soon.
Now the interactions are always the full log and the items
will get an increasing anonymised number so they will all appear different and
you can append

Daniel
