### ISSUE TITLE
Online interactions until 01.May

### ISSUE THREAD

**Issue by admdns** [recsyschallenge/2017#46]
Any hope https://recsys.xing.com/data/online will be updated until 01.May, since the interactions there are cut at 24.April ?

**Comment by dkohlsdorf** [comment]
Nope this is what you get as training sorry, we didn’t have time to grab more. We might do another batch in the middle of the challenge.

Hope this helps.
Daniel

**Comment by admdns** [comment]
Another problem is that the content information of items in interactions.csv (for the day 01.May) do not exist. So, this sort of looks like interactions of target users with unknown items. Can you include this content information as well?
