### ISSUE TITLE
Question about "num_accepted_recos"

### ISSUE THREAD

**Issue by tawatawara** [recsyschallenge/2017#47]
Hi, I have a question about  `num_accepted_recos`.
I submitted the file which includes 7316 user-item pairs, then I got the response as below:
```bash
{"num_accepted_recos":1476}
``` 
However, the submission I got by [GET /api/online/submission](https://github.com/recsyschallenge/2017/tree/master/api#get-apionlinesubmission) includes 7316 user-item pairs, and this file's content is same as the file I submitted. (and,  each user appears there only once. )

What is this difference ?  I misunderstand the meaning of `num_accepted_recos` (the number of user-item pairs) ?

Thanks,

team chome

**Comment by dkohlsdorf** [comment]
We have some problems with timeouts.
I will look into it today. However,
try to submit the not accepted multiple times
and use the get/submission endpoint to check if it worked.

Daniel

**Comment by tawatawara** [comment]
Thanks, and I have another question.

My assumptions is that `num_accepted_recos` is smaller than the true value but the submission got by [GET /api/online/submission](https://github.com/recsyschallenge/2017/tree/master/api#get-apionlinesubmission) was really accepted.

 Am I right ?

**Comment by dkohlsdorf** [comment]
Correct!
