### ISSUE TITLE
Daily online interactions

### ISSUE THREAD

**Issue by hackebeil** [recsyschallenge/2017#49]
Hi guys.

Regarding the interaction data we are supposed to retrieve daily via /api/online/data/interactions, we were wondering why the number of recorded interactions is so low compared to the training data we received earlier. It seems like there is a filter based on the target items of the previous day(s). But the same cannot be said for the users. We found some users in the interactions that are not contained in our target users. Does this mean that we also receive interactions for users that are target users of other teams. If so, can we also see what other teams are recommending via the impressions?

Thanks.

**Comment by dkohlsdorf** [comment]
yes it is filtered for items. users in the interactions should only include the ones from the targets. if there are more ignore them for now.
