### ISSUE TITLE
Impressions in daily online interactions

### ISSUE THREAD

**Issue by hackebeil** [recsyschallenge/2017#50]
Hi guys.

In the online interactions we receive every day, there are also some impressions (interaction_type = 0). However, compared to the number of recommendations we requested to give to users on the previous day, the interactions of the following day do not contain nearly enough impressions (orders of magnitude less). At some point I read that the recommendations would be given out as push notifications. If this is the case, why do they seemingly not reach their targets? Or is this just a problem related to the interactions data?

Thanks.

**Comment by dkohlsdorf** [comment]
Not all your recommendations will be played out to the user.
We have filters in place.

Daniel
