### ISSUE TITLE
submission api still buggy?

### ISSUE THREAD

**Issue by admdns** [recsyschallenge/2017#51]
Hi, Although, I sanity-checked the submission file, POST /api/online/submission said it accepted about 1/5th of the recos. I split the file into 5 chunks and resubmitted, it accepted no new submissions. With GET /api/online/submission, I can see the initial submission without loss. So, might this a bug? I am confused.

**Comment by dkohlsdorf** [comment]
That might be ... will check. But if you got all of it back it is submitted.

Daniel

**Comment by admdns** [comment]
Does the response from GET /api/online/submission correspond to accepted recos only, or is it just a copy of the submitted file?

**Comment by dkohlsdorf** [comment]
The accepted recommendations. It is not a copy.

**Comment by admdns** [comment]
Although the submitted file passes the sanity checks, the accepted file does not ... One ambiguity I have spotted so far is adding a user for an item multiple times ::
$ cat accepted.csv | grep 2145047
2145047	..., **4439961, 4439961, 3381262, 3381262**

$ cat solution.csv | grep 2145047
2145047	... ,4439961,..., 3381262,...

Another ambiguity is that the accepted.csv seems to have more accepted recos than the submission system said it did.

**Comment by dkohlsdorf** [comment]
Ok will check if I have time, in the meanwhile dont worry to much.

Daniel

**Comment by dkohlsdorf** [comment]
Also please shoot me an email with your teamname so i can debug better.

Daniel

**Comment by admdns** [comment]
I already did on the weekend. Please accept my gtalk request. Will do it again now.

**Comment by dkohlsdorf** [comment]
Sorry, but i am receiving a lot of email with challenge questions. So you need debugging please do it via email and stay in the thread so I can assign issues to teams easier. Also I dont see your gchat .. so can u send me your handle?


Daniel
