### ISSUE TITLE
when will the submited item be pushed to real user?

### ISSUE THREAD

**Issue by Leavingseason** [recsyschallenge/2017#53]
hi,  I am wondering  at what time the system will push our submitted file to the end users.  
Is it exactly the time when we upload the file? I mean, since I am in UTC +8 time zone, the time I upload my submission file may be the midnight in your country, so definitely  the push can not receive well results.

**Comment by dkohlsdorf** [comment]
The push happens exactly then … 
but the push on the platform stays there until a user checks it

Daniel

**Comment by Leavingseason** [comment]
ok, I see, thanks. 
So the submitted items will stay quietly in the pool until a user open the app/webpage,   not in the form like  bubble in smartphone that will actively notice the user about the news?

**Comment by dkohlsdorf** [comment]
there will be a bubble on the web page highlighting a push notification. it stays until a user clicks it or deletes it.

Daniel
