### ISSUE TITLE
question about the weekly score

### ISSUE THREAD

**Issue by Leavingseason** [recsyschallenge/2017#59]
Sorry to bother you if I miss some information in rules statement...
What does the weekly score mean? The maximum daily score among the week, or the sum of daily scores of the week?

**Comment by fabianabel** [comment]
Given one week of interaction data, we calculate a score (= _weekly score_) using the [evaluation metrics](http://2017.recsyschallenge.com/#evaluation) that we also sued during the offline challenge. For each team, we then took the two best weekly scores. The sum of these top two weekly scores constitutes the score for the [final leaderboard](https://recsys.xing.com/leaders#final).
