### ISSUE TITLE
Submission API "Something went wrong while trying to upload solution"

### ISSUE THREAD

**Issue by ksharmar** [recsyschallenge/2017#60]
@dkohlsdorf  Hi, We get this error message on submitting with the online submission api, instead of getting the number of accepted recommendations - It was working fine till 19th May. Also on querying the api to check the submissions using XGET, it retrieves them (so not sure if the POST response is fault but it still accepted the recommendations) TEAM AMETHYST.
------------------------------------------------------------
{"message":"Something went wrong while trying to upload solution. Contact the organizers if the problem remains: https://github.com/recsyschallenge/2017/issues"}
HTTP/1.1 200 OK
X-Runtime: 1.899566
X-Logjam-Request-Id: recommenders-production-d4b1f3b63e7f11e7b9e40242ac110002
Content-Length: 126325
Content-Type: text/plain; charset=utf-8
Date: Sun, 21 May 2017 23:47:22 GMT

2286337	1747771
2289630	12000216, 3708444
2290584	17846560, 6558585, 11712425, 12649429
2287462	10671836, 12970816, 15262549, 4253496, 9458753, 12284601, 4523515
2288764	15097765, 12629185, 18571863
2291069	17379510
.....

**Comment by fabianabel** [comment]
Sorry that we could not reproduce the issue and fix it for you!
