### ISSUE TITLE
Features details &  Evaluation: Title, Tags, Job roles & definition for itemSuccess(...)

### ISSUE THREAD

**Issue by afcarvalho1991** [recsyschallenge/2017#8]
#Hello,

I came across several questions after reading the challenge description.

* Q1: Is there any direct relation between tags, title or job roles?
* Q2: How detailed/domain specific are the existing tags? In e.g. https://www.xing.com/jobs/frankfurt-main-full-stack-developer-frankfurt-75-000-28390260

  What tags could one expect to be included? More like: 
  1. mission, awesome, responsibility, Client, small team, insights;
  2. SAAS, Full Stack Developer, software development.

* Q3: does itemSuccess(...) is considered during the offline phase? If so, what is a successful push recommendation?

Thank you,
André

**Comment by fabianabel** [comment]
Hi André, 

good questions! Let me try to answer: 

- Q1: no, there is no explicit, direct relationship between tags, title keywords and jobroles, but `users.jobroles` are, for example, likely to appear in `items.title` 
- Q2: 
  + for the particular example, you could expect tags such as PHP, html, css, jquery, mysql, ...
  + IDs that may appear as tags, jobroles, titles actually refer to concepts in a taxonomy that we build up at XING. This taxonomy features synonym lists (e.g. "Java Software Engineer" and "Java Software Developer" would refer to the same concept). 
  + tags, jobroles, etc. have a different level of specificity (e.g. ranging from broad concepts like "Management" to more specific concepts such as "CSS 3" or "responsive web design")
  + the taxonomy features both hard, technical concepts such as "SAAS" as well as soft skills/concepts such as "leadership skills" or "intercultural competence"
- Q3: yes, it is part of the [evaluation metrics](http://2017.recsyschallenge.com/#evaluation). If for a given item, at least one user received a successful recommendation then this will bring in 50 points for paid items and 25 points for non-paid items. 

Cheers,
fabian

**Comment by afcarvalho1991** [comment]
Thank you @fabianabel !

I think it this can be close now.
