### ISSUE TITLE
What's the meaning of 23?

### ISSUE THREAD

**Issue by jbochi** [recsyschallenge/2017#9]
Baseline model does not count a [discipline match](https://github.com/recsyschallenge/2017/blob/master/baseline/model.py#L51) or [industry match](https://github.com/recsyschallenge/2017/blob/master/baseline/model.py#L45) if id is 23. Does this number have a special meaning?

**Comment by dkohlsdorf** [comment]
23 is the default id .. however since we are anonymising it, it would be better to keep it.
I will fix it.

Daniel
